documentation:
- changed-files:
  - any-glob-to-any-file:
    - .readthedocs.yml
    - CITATION
    - doc/**/*
    - ginga/doc/*
    - licenses/*
    - '*.md'
    - '*.txt'
  - all-globs-to-any-file:
    - '*.rst'
    - '!CHANGES.rst'

maintenance:
- changed-files:
  - any-glob-to-any-file:
    - .bandit.yaml
    - .github/**/*
    - .gitignore
    - conftest.py
    - MANIFEST.in
    - pyproject.toml
    - setup.*

plugin:
- changed-files:
  - any-glob-to-any-file:
    - doc/manual/plugins.rst
    - doc/manual/plugins_global/**/*
    - doc/manual/plugins_local/**/*
    - experimental/plugins/*
    - ginga/rv/plugins/*

reference viewer:
- changed-files:
  - any-glob-to-any-file:
    - ginga/rv/**/*

widget:
- changed-files:
  - any-glob-to-any-file:
    - doc/dev_manual/jupnotebooks.rst
    - ginga/aggw/**/*
    - ginga/gtk3w/**/*
    - ginga/gw/**/*
    - ginga/qtw/**/*
    - ginga/web/**/*
