[build-system]
requires = ["setuptools>=64",
            "setuptools_scm[toml]>=7",
            "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "ginga/version.py"
version_scheme = "release-branch-semver"
