#
# Define cursors for Ginga
#
# Each cursor should be defined with the following attributes:
#   file: name of the cursor (relative to ginga.cursors, if it doesn't
#          begin with a '/')
#   scale_width: scaling factor for width from default length
#   scale_height: scaling factor for height from default length
#   point_x_pct: percent offset from (0, 0) for the X point of the cursor
#   point_y_pct: percent offset from (0, 0) for the Y point of the cursor
#

[defaults]
dim_px = 16

[cursors]

[cursors.pick]
file = 'cross.svg'
scale_width = 1.0
scale_height = 1.0
point_x_pct = 0.5
point_y_pct = 0.5

[cursors.pan]
file = 'hand.svg'
scale_width = 1.0
scale_height = 1.53
point_x_pct = 0.5
point_y_pct = 0.5
    
[cursors.draw]
file = 'pencil.svg'
scale_width = 1.5
scale_height = 1.5
point_x_pct = 0.0
point_y_pct = 0.95

[cursors.zoom]
file = 'magnify.svg'
scale_width = 2.0
scale_height = 2.0
point_x_pct = 0.385
point_y_pct = 0.385
