name: When Opened

on:
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9  # v5.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
