name: When Opened

on:
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b  # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
